apiVersion: v1
kind: Pod
metadata:
  name: secret-files-test-pod
spec:
  containers:
    - name: test-container
      image: kubernetes/mounttest:0.1
      command: [ "/mt", "--file_content=/etc/secret-volume/special/path/__special_thing.dat" ]
      volumeMounts:
          # name must match the volume name below
          - name: secret-volume
            mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret:
        items:
          - name: test-secret
            key: data-1
            path: special/path/__special_thing.dat
  restartPolicy: Never
